-- Product-Wise Sales With Product Name.
select
  p.ProductID,
  p.ProductName,
  sum(o.Total) as Sales
from `e1.products` as p
inner join `e1.order_items` as o 
on p.ProductID = o.ProductID
group by p.ProductName, p.ProductID ;

-- CategoryName-Wise total Sales.
select
  c.CategoryID,
  c.CategoryName,
  sum(o.Total) as TotalSales
from `e1.products` as p 
inner join `e1.order_items` as o 
on p.ProductID = o.ProductID
inner join `e1.categories` as c
on c.CategoryID = p.CategoryID
group by c.CategoryID, c.categoryName 
order by TotalSales desc ;

-- Calculate total sales generated by products from each supplier.
select
  s.SupplierName,
  s.SupplierID,
  sum(o.Total) as TotalSale
from `e1.products` as p
inner join `e1.order_items` as o
on p.ProductID = o.ProductID
inner join `e1.suppliers` as s
on s.SupplierID = p.SupplierID
group by s.SupplierName, s.SupplierID
order by TotalSale desc ;
