-- How many different products are there overall 
select count(ProductID)
from `e1.products` ;

-- How many products are there in each category
select 
  CategoryID,
  count(*) as Total_count
from `e1.products`
group by CategoryID ;

-- How many units of each category have been sold
select 
  ProductID,
  sum(Quantity) as Units_sold 
from `e1.order_items`
group by ProductID ;

-- What is the total sales value generated by each product
select 
  ProductID,
  sum(Total) as Total_Sales
from `e1.order_items`
group by ProductID ;

-- What was the average selling price at which each product was sold
select 
  ProductID,
  avg(SellingPrice) as AvgPrice
from `e1.order_items`
group by ProductID ;

--What was the lowest and highest selling price recorded for each products
select 
  ProductID,
  max(SellingPrice) as Highest,
  min(SellingPrice) as Lowest
from `e1.order_items`
group by ProductID ;

-- For each of the order status what is the number of orders for each of the customer?
select 
  CustomerID,
  Status,
  count(*) as NumberOfOrders
from `e1.orders`
group by Status, CustomerID ;

-- How many inventory records are maintained for each warehouse
select
  WarehouseID,
  count(Stock) as Records
from `e1.inventory`
group by WarehouseID;

-- How many orders are entered by each of the employees for each status
select 
  EmployeeID,
  Status,
  count(*) OrdersEntered
from `e1.orders`
group by EmployeeID, Status ;

-- How many products in each category have an MRP above 2000rs
select 
  CategoryID,
  count(*) as NumberOfProducts
from `e1.products`
where MRP > 2000
Group by CategoryID ;

-- What is the total quantity sold for each product when quantity is greater than 1
select 
  ProductID,
  sum(Quantity) as ProductsSold
from `e1.order_items`
where Quantity > 1
Group by ProductID ;

-- What is the average payment for each payment methode among successful payments
select 
  Method,
  round(avg(Amount),2) as AvgPayment
from `e1.payments`
where Status = "Success"
group by Method ;
