-- JOINTES --

-- Show me the products name and the category name.
  -- Products --> Products Name
  -- linkage : categoryID
  -- Category --> Category Name

select 
  p.ProductID,
  p.ProductName,
  c.CategoryID,
  c.CategoryName
from `e1.categories` as c
inner join `e1.products` as p
on c.CategoryID = p.CategoryID ;

--Display products belonging to the Electronics category
select 
  p.ProductID,
  p.ProductName,
  c.CategoryID,
  c.CategoryName
from `e1.categories` as c
inner join `e1.products` as p
on c.CategoryID = p.CategoryID 
where c.CategoryName = "Electronics" ;

-- Display products with their category names, sorted by MRP from highest to lowest.
select 
  p.ProductID,
  p.ProductName,
  c.CategoryID,
  c.CategoryName
from `e1.categories` as c
inner join `e1.products` as p
on p.CategoryID = c.CategoryID
order by p.MRP desc ;

-- Display ProductName, CategoryName and discount amount.
select 
  p.ProductID,
  p.ProductName,
  c.CategoryID,
  c.CategoryName,
  p.MRP - p.SellingPrice as Discount
from `e1.products` as p
inner join `e1.categories` as c
on p.CategoryID = c.CategoryID ;

-- Display each product along with its supplier name and supplier state.
select 
  p.ProductID,
  p.ProductName,
  s.SupplierName,
  s.State
from `e1.products` as p
inner join `e1.suppliers` as s
on p.SupplierID = s.SupplierID ;

--Display all Cancelled customer orders along with customer name and city.
select 
  c.CustomerID,
  c.Name,
  c.City,
  o.Status
from `e1.customers` as c
inner join `e1.orders` as o
on c.CustomerID = o.CustomerID
where o.Status = "Cancelled" ;

-- Calculate total sales value for every order.
select
  o.OrderID,
  sum(oi.Total) as TotalSale
from `e1.orders` as o
inner join `e1.order_items` as oi
on o.OrderID = oi.OrderID
group by o.OrderID ;

-- Calculate total sales value generated by each customer.
select
  c.CustomerID,
  sum(oi.Total) as TotalSale
from `e1.customers` as c
inner join `e1.orders` as o
on c.CustomerID = o.CustomerID
inner join `e1.order_items` as oi
on o.OrderID = oi.OrderID
group by c.CustomerID
order by TotalSale desc ;









