#A store sells four products.

#Prices:
#[250, 400, 750, 1200]

#Units sold:
#[12, 8, 5, 10]

#Calculate the revenue generated by each product.
#The store then wants to increase the revenue figures by 5% for forecasting purposes.

import numpy as np 

prices = np.array([250, 400, 750, 1200])
units = np.array([12, 8, 5, 10])

print("Revenue : ", prices*units)
print("Forcasting Revenue : ", (prices*units)*1.05)
